#!/usr/bin/env node
// verify-pack.mjs — does a skill pack actually work on a host with no MCP plugin?
// Version: 2.0.0 (2026-09-28) — checks 6-8 (retired KB citations, connection-name
// literals, version-pinned cache paths) turn "look for known-bad names" into
// checks that fail on the CLASS (Smith #1013 RC-2, F9, F11, F12).
//
// CANONICAL SOURCE: o-matic-studio/scripts/verify-pack.mjs. The copies in
// o-matic-firm and o-matic-agency are generated by scripts/sync-pack-tooling.mjs
// and its --check fails on drift (Smith #1013 F12: four copies, three variants).
// Exit 1 on any FAIL. Every rule here encodes a failure this factory has already had.
import { readFileSync, readdirSync, existsSync, statSync, lstatSync } from "node:fs";
import { createHash } from "node:crypto";
import { join, basename } from "node:path";

const root = process.argv[2];
if (!root) { console.error("usage: verify-pack.mjs <marketplace-root>"); process.exit(2); }
let fails = 0, warns = 0, checks = 0;
const FAIL = (m) => { console.log(`  FAIL  ${m}`); fails++; };
const WARN = (m) => { console.log(`  warn  ${m}`); warns++; };
const OK   = (m) => { console.log(`  ok    ${m}`); };
// Do NOT follow symlinks: host-discovery shims (.agents/skills -> ../<pack>/skills)
// point at the same files, and walking both reports every finding twice.
const walk = (d) => readdirSync(d).flatMap(f => {
  const p = join(d, f);
  if (lstatSync(p).isSymbolicLink()) return [];
  return statSync(p).isDirectory() ? walk(p) : [p];
});

// Tools that exist. Anything else called as an instruction is a ghost.
const SERVER_TOOLS = ["startup","factory_query","search","connections_list","embed_query","omatic_guide"];
const DEAD_PLUGIN_TOOLS = ["omatic_select_factory","omatic_resolve_factory","omatic_runtime_status","omatic_usage_guide",
  "omatic_execute_sql","omatic_search_memory","omatic_factory_startup_run","omatic_factory_startup"];
// A line may NAME a dead thing to forbid it. These words mark that intent.
const EXEMPT = /retired|forbid|do not call|do(es)? not exist|no longer exist|no longer|stale|decommission|superseded|previous text|history|historic|not a typo|removed in|gone, not deprecated|unknown tool|deleted, not deprecated|absent|there is no|ships no|no mcp server|pack note/i;

console.log(`\n=== verifying ${root} ===\n`);

// 1. marketplace manifest
const mkPath = join(root, ".claude-plugin", "marketplace.json");
checks++;
if (!existsSync(mkPath)) FAIL(".claude-plugin/marketplace.json missing");
else {
  let mk; try { mk = JSON.parse(readFileSync(mkPath, "utf8")); OK("marketplace.json parses"); }
  catch (e) { FAIL(`marketplace.json invalid JSON: ${e.message}`); }
  if (mk) {
    if (!mk.name) FAIL("marketplace.json has no name");
    if (!Array.isArray(mk.plugins) || !mk.plugins.length) FAIL("marketplace.json lists no plugins");
    for (const p of mk.plugins ?? []) {
      const src = join(root, p.source ?? "");
      if (!existsSync(src)) FAIL(`plugin source missing: ${p.name} -> ${p.source}`);
      else OK(`plugin source resolves: ${p.name}`);
    }
  }
}

// 2. per-plugin manifests + the no-MCP invariant
for (const d of readdirSync(root)) {
  const pd = join(root, d);
  if (!statSync(pd).isDirectory() || d.startsWith(".")) continue;
  const cp = join(pd, ".claude-plugin", "plugin.json");
  if (!existsSync(cp)) continue;
  checks++;
  let pj; try { pj = JSON.parse(readFileSync(cp, "utf8")); OK(`${d}/plugin.json parses`); }
  catch (e) { FAIL(`${d}/plugin.json invalid: ${e.message}`); continue; }
  // A SKILL pack must not declare an MCP server; a TOOL pack must. The
  // marketplace metadata says which this is, so the invariant is checked
  // against intent rather than assumed.
  const mkRaw = existsSync(mkPath) ? readFileSync(mkPath, "utf8") : "";
  const isToolPack = /"shipsMcpServer"\s*:\s*true/.test(mkRaw);
  const hasMcp = Boolean(pj.mcpServers) || existsSync(join(pd, ".mcp.json"));
  if (isToolPack) {
    if (hasMcp) OK(`${d}: tool pack ships an MCP server, as declared`);
    else FAIL(`${d}: declared shipsMcpServer=true but no mcpServers/.mcp.json found`);
  } else {
    if (hasMcp) FAIL(`${d}: skill pack DECLARES mcpServers — restricted hosts will omit it`);
    else OK(`${d}/plugin.json declares no mcpServers`);
  }
  if (!pj.skills) WARN(`${d}/plugin.json has no skills path`);

  // .claude-plugin and .codex-plugin manifests must ship in lockstep on
  // version (task #803, the same defect measured in o-matic-agency: 1.4.12
  // and 1.4.13 each bumped only .claude-plugin and silently left
  // .codex-plugin behind, two releases of drift with nothing to catch it).
  // Manifest SHAPE is not enforced (the two hosts have genuinely different
  // schemas -- codex nests display fields under "interface", claude does
  // not -- so only "version" is compared).
  const codexCp = join(pd, ".codex-plugin", "plugin.json");
  if (existsSync(codexCp)) {
    let cj; try { cj = JSON.parse(readFileSync(codexCp, "utf8")); }
    catch (e) { FAIL(`${d}/.codex-plugin/plugin.json invalid: ${e.message}`); cj = null; }
    if (cj) {
      if (cj.version !== pj.version)
        FAIL(`${d}: version drift -- .claude-plugin/plugin.json is ${pj.version}, .codex-plugin/plugin.json is ${cj.version}`);
      else OK(`${d}: .claude-plugin and .codex-plugin versions match (${pj.version})`);
    }
  }
}

// 2b. compatibility tier must be declared — known_rules #284 is halt-grade
{
  checks++;
  const mkTxt = existsSync(mkPath) ? readFileSync(mkPath, "utf8") : "";
  if (/compatibilityTier/.test(mkTxt)) OK("compatibility tier declared (rule #284)");
  else FAIL("no compatibilityTier declared — rule #284 (compatibility gate) is halt-grade");
}

// A skill whose JOB is detecting retired mechanisms must name them to detect
// them. Scanning it for "names a retired mechanism" is the same false positive
// this factory has now hit three times in one day: v_retired_role_references
// fired on the ticket written to retire the roles, v_decommission_audit fired
// 5/5 on records that say "retained verbatim as historical evidence", and this
// check fired 11/11 on the staleness auditor's own detection vocabulary.
//
// Exempt by ROLE, not by phrase. A denylist of wordings keeps firing on every
// well-written retirement record; the detector is exempt because detecting is
// what it is for. Its DESCRIPTION is still checked below -- that is the routing
// text hosts read, and it must not read as a live Conductor instruction.
const RETIREMENT_DETECTORS = new Set(["factory-staleness-audit"]);

// 3. every SKILL.md
for (const f of walk(root).filter(p => basename(p) === "SKILL.md")) {
  const rel = f.replace(root, ".");
  const txt = readFileSync(f, "utf8");
  checks++;
  const fm = txt.match(/^---\n([\s\S]*?)\n---/);
  if (!fm) { FAIL(`${rel}: no frontmatter`); continue; }
  const name = (fm[1].match(/^name:\s*(.+)$/m) || [])[1]?.trim();
  const desc = (fm[1].match(/^description:\s*(.+)$/m) || [])[1]?.trim();
  const dir = basename(f.replace(/\/SKILL\.md$/, ""));
  if (!name) FAIL(`${rel}: frontmatter has no name`);
  else if (name !== dir) FAIL(`${rel}: name '${name}' != directory '${dir}'`);
  if (!desc) FAIL(`${rel}: frontmatter has no description`);
  else if (/conductor/i.test(desc)) FAIL(`${rel}: DESCRIPTION names Conductor — this is the routing text hosts read`);

  // Scan by PARAGRAPH, not line: a prohibition marker on the first line of a
  // blockquote or paragraph exempts the whole construct. Line-granular scanning
  // flags the continuation lines of every "Conductor is retired" warning, and a
  // check that cries wolf is a check nobody runs.
  let para = [], startLine = 1;
  const flush = () => {
    if (!para.length) return;
    const block = para.join("\n");
    // A whole-paragraph exemption is too coarse: a paragraph can carry a LIVE
    // instruction and an unrelated historical clause ("...removed in 5.0.0"),
    // and the historical clause was clearing the live one. This shipped a real
    // Conductor instruction to GitHub on 2026-08-24. Exempt a paragraph only
    // when it is a blockquote prohibition; otherwise judge line by line.
    const isBlockquote = para.every((l) => l.trimStart().startsWith(">"));
    const isDetector = [...RETIREMENT_DETECTORS].some((d) => rel.includes(d));
    if (!isDetector && !(isBlockquote && EXEMPT.test(block))) {
      para.forEach((line, k) => {
        const n = startLine + k;
        if (EXEMPT.test(line)) return;              // the LINE itself disowns it
        if (/8438/.test(line)) FAIL(`${rel}:${n}: routes to dead port 8438`);
        else if (/\bconductor\b/i.test(line)) FAIL(`${rel}:${n}: names Conductor as live instruction`);
        for (const t of DEAD_PLUGIN_TOOLS)
          if (line.includes(t)) FAIL(`${rel}:${n}: calls ${t} — no plugin ships in this pack`);
      });
    }
    para = [];
  };
  txt.split("\n").forEach((line, i) => {
    if (line.trim() === "") { flush(); startLine = i + 2; return; }
    if (!para.length) startLine = i + 1;
    para.push(line);
  });
  flush();

  // shared fragment integrity
  const s = txt.indexOf("<!-- shared:system-5-detection start -->");
  const e = txt.indexOf("<!-- shared:system-5-detection end -->");
  if (s !== -1 && e === -1) FAIL(`${rel}: shared block opened but never closed`);
}


// 4. PERSONA GOLD RECORD — the file-side half of the release gate (task #745).
//
// WHY THIS EXISTS. The persona release gate is three sets of DB triggers on
// factory.persona* (trg_persona_publish_gate, six trg_persona_*_integrity_gate,
// trg_persona_build_release_gate), proven to refuse 9/9 in
// factory.fn_persona_gate_selftest(). Every one of them fires ONLY on a
// database write. A skill authored as a FILE and shipped without ever recording
// a persona_build row is invisible to all of them — persona_build's own FK
// refuses the build row with SQLSTATE 23503 before the release gate is even
// reached, so the gate cannot even be ASKED about an ungoverned persona.
//
// Measured 2026-09-15: six skills ship from files whose persona_version is
// review_status='draft' with ZERO persona_build rows — andy (the pixel-photo-
// coach skill, shipping 2.5.0), brandy, carver, jake, jo, monet. The database
// gate refused nothing in any of those six cases because it was never reached.
//
// WHY AN ATTESTATION FILE AND NOT A QUERY. verify-pack runs offline, in CI, on
// a host with no database and no credentials. A check that needs a connection
// is a check that gets skipped in the one place it must run. So the database
// exports what it certified into persona-attestation.json (see
// persona-attest-export.sql, which is the query that generates it) and this
// check verifies the PACK against that export.
//
// IT FAILS CLOSED, DELIBERATELY. A missing attestation file, a skill absent
// from it, or a stale skill version all FAIL. A skip would reproduce this
// factory's signature defect — absence indistinguishable from success — inside
// the control written to catch exactly that.
const attPath = join(root, "persona-attestation.json");
const skillDirs = walk(root)
  .filter(p => basename(p) === "SKILL.md")
  .map(p => basename(p.replace(/\/SKILL\.md$/, "")));

checks++;
if (!skillDirs.length) {
  OK("persona gold record: pack ships no skills");
} else if (!existsSync(attPath)) {
  FAIL(`persona-attestation.json missing — ${skillDirs.length} skill(s) ship with no ` +
       `proof their persona was ever certified. Generate it with persona-attest-export.sql.`);
} else {
  let att;
  try { att = JSON.parse(readFileSync(attPath, "utf8")); OK("persona-attestation.json parses"); }
  catch (e) { FAIL(`persona-attestation.json invalid JSON: ${e.message}`); }
  if (att) {
    const bySkill = new Map((att.personas ?? []).map(x => [x.skill, x]));
    if (!att.generated_at || !att.tenant) FAIL("persona-attestation.json has no generated_at/tenant provenance");
    for (const dir of skillDirs) {
      checks++;
      const rec = bySkill.get(dir);
      if (!rec) {
        FAIL(`${dir}: not in persona-attestation.json — ships with no gold record at all`);
        continue;
      }
      const why = [];
      if (rec.review_status !== "published") why.push(`review_status='${rec.review_status}'`);
      if (!rec.identity_signature)           why.push("no identity_signature");
      if (!(rec.character_bible > 0))        why.push("no character bible");
      if (!(rec.dimensions > 0))             why.push("zero character dimensions");
      if (!(rec.builds > 0))                 why.push("no persona_build row — the release gate never ran");
      if (why.length) FAIL(`${dir}: persona '${rec.agent_name}' is not shippable — ${why.join("; ")}`);
      else OK(`${dir}: persona '${rec.agent_name}' certified (v${rec.version}, ${rec.builds} build(s))`);
    }
    // A persona attested but no longer shipped is drift in the other direction.
    for (const rec of att.personas ?? [])
      if (!skillDirs.includes(rec.skill))
        WARN(`persona-attestation.json lists '${rec.skill}' but the pack ships no such skill`);
  }
}


// 5. RETIRED PERSONA NAME DETECTOR (task #777). A persona rename — Pixel ->
// Andy (decision #538), Rimmer -> Smith (decision #416) — must be caught by a
// gate, not by the operator reading a diff by hand. scripts/retired-persona-
// allowlist.json lists {name, replaced_by, decision, reason} for every retired
// persona name relevant to THIS pack.
//
// Scope, deliberately narrow: only files a host actually LOADS as instruction
// or routing metadata — SKILL.md, and anything under adapters/ or contracts/.
// A CHANGELOG, an audit record, or a reference README is supposed to name a
// retired persona; that is how history gets written down, and scanning those
// genres for it is the same false-positive shape check 3's own EXEMPT comment
// already documents three times over. The risk this check exists for is a
// retired name surviving in something a host still reads as live routing.
//
// Matching is CASE-SENSITIVE on the capitalized form (e.g. "Pixel", not
// "pixel"). "Pixel" collides with the ordinary English noun for a picture
// element, which this pack's own photography domain uses constantly ("measure
// a single pixel", "pixel-forensics", "pixel statistics") — a case-insensitive
// match fails on every one of those. The persona name is always written
// capitalized as a proper noun; the common noun is not.
//
// Exemption is WHOLE-PARAGRAPH here, unlike check 3's line-by-line rule for
// retired mechanisms. A retired persona is explained in continuous prose
// ("the precedent is X: his lane became Y... because his skill was removed"),
// not a one-line "call this dead tool" instruction sitting next to an
// unrelated historical aside — so paragraph-level judgment fits this domain
// without reopening the false-negative gap check 3 was built against.
const PERSONA_SCAN_SCOPE = (rel) => /SKILL\.md$/.test(rel) || /\/(adapters|contracts)\//.test(rel);
const PERSONA_EXEMPT = new RegExp(EXEMPT.source + "|replac|successor|former |is gone|renamed|rename\\b|moved to|four.step|became|\\bremoved\\b", "i");
{
  const raPath = join(root, "scripts", "retired-persona-allowlist.json");
  checks++;
  if (!existsSync(raPath)) {
    WARN("no scripts/retired-persona-allowlist.json — retired-persona-name detector has nothing to check against (task #777)");
  } else {
    let ra;
    try { ra = JSON.parse(readFileSync(raPath, "utf8")); OK("retired-persona-allowlist.json parses"); }
    catch (e) { FAIL(`retired-persona-allowlist.json invalid JSON: ${e.message}`); }
    const retired = (ra?.retired ?? []).filter(r => {
      if (!r.name || !r.replaced_by || !r.reason) {
        FAIL(`retired-persona-allowlist.json entry missing name/replaced_by/reason: ${JSON.stringify(r)}`);
        return false;
      }
      return true;
    });
    if (ra && !retired.length) OK("retired-persona-allowlist.json declares no retired names for this pack");
    const escape = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);
    // case-INsensitive, whole-token match against a directory's hyphen/underscore
    // segments — a narrow, deliberate context, not free prose, so the common-word
    // collision risk that rules out case-insensitivity below does not apply here.
    const dirHasSegment = (dir, name) =>
      dir.split(/[-_]/).some(seg => seg.toLowerCase() === name.toLowerCase());
    // case-SENSITIVE on the capitalized proper-noun form for prose scanning.
    const proseRe = (n) => new RegExp(`\\b${escape(cap(n))}\\b`);

    // a) a skill's own identity must never BE a retired name — no context
    //    exempts a skill from naming itself after a persona that no longer exists.
    for (const dir of skillDirs) {
      checks++;
      for (const r of retired)
        if (dirHasSegment(dir, r.name))
          FAIL(`${dir}: skill directory IS a retired persona name ('${r.name}', replaced by '${r.replaced_by}' — ${r.decision})`);
    }

    // b) SKILL.md / adapters / contracts, whole paragraph at a time.
    if (retired.length) {
      for (const f of walk(root).filter(p => p.endsWith(".md"))) {
        const rel = f.replace(root, ".");
        if (!PERSONA_SCAN_SCOPE(rel)) continue;
        const txt = readFileSync(f, "utf8");
        checks++;
        let para = [], startLine = 1;
        const flush = () => {
          if (!para.length) return;
          const block = para.join("\n");
          if (!PERSONA_EXEMPT.test(block)) {
            for (const r of retired)
              if (proseRe(r.name).test(block))
                FAIL(`${rel}:${startLine}: names retired persona '${r.name}' as a live reference — replaced by '${r.replaced_by}' (${r.decision})`);
          }
          para = [];
        };
        txt.split("\n").forEach((line, i) => {
          if (line.trim() === "") { flush(); startLine = i + 2; return; }
          if (!para.length) startLine = i + 1;
          para.push(line);
        });
        flush();
      }
    }
  }
}


// Files a host LOADS as instruction, routing, or runtime behavior. History
// genres (CHANGELOG, audits, migrations, reference READMEs) are supposed to
// name retired things and are out of scope, the same judgment check 5 makes.
const LOADED = (rel) =>
  !/CHANGELOG\.md$|\/audits\/|\/migrations\/|\/reference\//.test(rel) &&
  (/SKILL\.md$/.test(rel) || /\/(adapters|contracts|evals|hooks)\//.test(rel)) &&
  /\.(md|ya?ml|mjs|js|py|sh|json)$/.test(rel);
const loadedFiles = walk(root).map((f) => [f, f.replace(root, ".")]).filter(([, rel]) => LOADED(rel));
const CITE_EXEMPT = /retired|superseded|replac|successor|split into|do not cite|not current|formerly|was the/i;

// 6. RETIRED KB CITED AS CURRENT AUTHORITY (Smith #1013 F9, Data H3). The
// retired set is exported from Commons kb.documents.status into
// scripts/retired-kb.json — the structured column, never a document's own prose
// (KB-0411 still says "Status: active" in its body). A line that cites a retired
// KB number must itself say it is retired or superseded; otherwise it is being
// served as current. KB-0051 was cited as live authority in seven places.
{
  const rkPath = join(root, "scripts", "retired-kb.json");
  checks++;
  if (!existsSync(rkPath)) FAIL("scripts/retired-kb.json missing — the retired-KB detector has nothing to check against (fails closed)");
  else {
    let rk; try { rk = JSON.parse(readFileSync(rkPath, "utf8")); } catch (e) { FAIL(`retired-kb.json invalid: ${e.message}`); }
    const retiredIds = new Map((rk?.retired ?? []).map((r) => [r.id, r]));
    if (rk && !retiredIds.size) FAIL("retired-kb.json lists no retired documents — an empty list makes this check vacuous");
    else if (rk) OK(`retired-kb.json: ${retiredIds.size} retired document(s) (exported ${rk.exported_at})`);
    for (const [f, rel] of loadedFiles) {
      readFileSync(f, "utf8").split("\n").forEach((line, k) => {
        for (const m of line.matchAll(/\bKB-?0*(\d{1,4})\b/g)) {
          const r = retiredIds.get(Number(m[1]));
          if (r && !CITE_EXEMPT.test(line))
            FAIL(`${rel}:${k + 1}: cites ${r.kb} as current authority — it is retired (${r.title})`);
        }
      });
    }
  }
}

// 7. CONNECTION NAME WRITTEN AS A LITERAL (Smith #1013 F2/F3). Connection names
// are operator-facing strings that get renamed ("o-MATIC Home Office" ->
// "o-MATIC  - Corp" -> "o-MATIC Foundry"); every literal copy went stale
// silently and a daily recorder lost its evidence to one. The class is "a
// connection passed as a quoted literal", not any particular spelling, so a
// future rename cannot slip past. Placeholders (<name>, ..., ${var}) are fine.
{
  checks++;
  const LIT = /\bconnection\s*[:=]\s*(["'`])([^"'`\n]{2,80})\1/g;
  const PLACEHOLDER = /[<>{}$]|\.\.\.|\bname\b|NAME|your |<|example/i;
  let hits = 0;
  for (const [f, rel] of loadedFiles) {
    readFileSync(f, "utf8").split("\n").forEach((line, k) => {
      for (const m of line.matchAll(LIT)) {
        if (PLACEHOLDER.test(m[2]) || /never|do not|don't|stale|renamed|was /i.test(line)) continue;
        hits++;
        FAIL(`${rel}:${k + 1}: connection name written as a literal ("${m[2]}") — read it off the wire (startup / connections_list, match database), never from a file`);
      }
    });
  }
  if (!hits) OK("no connection name is written as a literal in a loaded file");
  // Same class, one layer down (Smith #1013 F5/F6/F7): an estate's private
  // server written into anything a pack ships. Operator ruling 2026-09-30:
  // "they shouldn't be looking for any tailscale or private servers." This
  // scans EVERY text file in the repository, not only the files a host loads:
  // the first version scanned loaded files only, and a CHANGELOG carried the
  // operator's private Control Room URL through release 1.4.20 unseen.
  const PRIVATE_NAME_SHA256 = new Set(["9274d49c27b7583a60a06420b820077e38c6ad785f6df54b667d42aa9a5b325c", "9731971c9b2dfb957a786ef661835fc1fb1d12886a9c290d1933545aa600c44d"]); // one operator's private host and tailnet names, stored hashed so no shipped file spells them
const namesPrivate = (line) => (line.toLowerCase().match(/[a-z0-9-]{6,}/g) || []).some((w) => PRIVATE_NAME_SHA256.has(createHash("sha256").update(w).digest("hex")));
const PRIVATE = [
    [/https?:\/\/[A-Za-z0-9.-]+\.ts\.net\b/, "a private tailnet address"],
    [/\b[A-Za-z0-9-]+\.[A-Za-z0-9-]+\.ts\.net\b/, "a private tailnet host"],
        [/\/Users\/[a-z][A-Za-z0-9_-]+\//, "one person's home folder"],
    [/\/Volumes\/NVMe/, "one machine's disk path"],
  ];
  const shipped = walk(root).filter((f) => !/\/(\.git|node_modules|\.build)\//.test(f) && !/verify-pack\.mjs$/.test(f) && /\.(md|ya?ml|mjs|js|cjs|ts|py|sh|json|txt|toml|swift)$/.test(f));
  let hosts = 0;
  for (const f of shipped) {
    const rel = f.replace(root, ".");
    readFileSync(f, "utf8").split("\n").forEach((line, k) => {
      if (namesPrivate(line)) { hosts++; FAIL(`${rel}:${k + 1}: ships one operator's private server or tailnet name — a pack runs on strangers' machines`); return; }
      for (const [re, what] of PRIVATE) {
        if (re.test(line)) { hosts++; FAIL(`${rel}:${k + 1}: ships ${what} — a pack runs on strangers' machines and must never name or look for a private server`); break; }
      }
    });
  }
  if (!hosts) OK(`no private server, tailnet host or personal path in any of ${shipped.length} shipped text files`);
}

// 8. VERSION-PINNED PLUGIN CACHE PATH (task #983). A path like
// .../plugins/cache/<marketplace>/<plugin>/<version>/... is correct for exactly
// one release and silently wrong after the next. Nothing a pack ships may carry
// one, whatever version it names.
{
  checks++;
  let hits = 0;
  for (const [f, rel] of loadedFiles) {
    readFileSync(f, "utf8").split("\n").forEach((line, k) => {
      if (/\/plugins\/cache\/[^/\s]+\/[^/\s]+\/\d+\.\d+[^/\s]*\//.test(line) && !/example|e\.g\.|such as|FAIL|stale/i.test(line)) {
        hits++;
        FAIL(`${rel}:${k + 1}: carries a version-pinned plugin cache path — resolve the installed root at load time instead`);
      }
    });
  }
  if (!hits) OK("no version-pinned plugin cache path in a loaded file");
}

console.log(`\n${fails ? "RESULT: FAIL" : "RESULT: PASS"} — ${checks} units checked, ${fails} fail, ${warns} warn\n`);
process.exit(fails ? 1 : 0);
